<?php
$mysqli_connection = new mysqli("localhost","root","");

$mysqli_connection->query("CREATE DATABASE IF NOT EXISTS Climate");

mysqli_select_db($mysqli_connection,'Climate');

$mysqli_connection->query("CREATE TABLE IF NOT EXISTS districts(ID INT(11) NOT NULL AUTO_INCREMENT,PRIMARY KEY(ID), NAME VARCHAR(30) NOT NULL)");

$mysqli_connection->query("CREATE TABLE IF NOT EXISTS members(ID INT(11) NOT NULL AUTO_INCREMENT,PRIMARY KEY(ID),NAME VARCHAR(30) NOT NULL,EMAIL VARCHAR(50) NOT NULL UNIQUE,PASSWORD VARCHAR(50) NOT NULL,DISTRICT_ID INT(11) NOT NULL,FOREIGN KEY(DISTRICT_ID)REFERENCES districts(ID))");

$mysqli_connection->query("CREATE TABLE tree_types(ID INT(11) NOT NULL AUTO_INCREMENT, PRIMARY KEY(ID),NAME VARCHAR(30) NOT NULL, DISTRICT_ID INT(11) NOT NULL,FOREIGN KEY(DISTRICT_ID) REFERENCES districts(ID),MEMBER_ID INT(11) NOT NULL,FOREIGN KEY(MEMBER_ID)REFERENCES members(ID))");